<?php

define('DRUPAL_BREAK', '<!--break-->');

// ideas ... maybe have an admin setting checkbox that allows the content to
// automatically insert <!--break--> only if that option is checked.


/**
 * Implements hook_block_view_alter().
 */
function islandora_datastream_blocks_html_teaser_block_view_alter(&$data, $block) {
  if ($block->module == 'islandora_datastream_blocks') {
    // does the content have a <!--break--> in it already??  if not, insert after the first </p>
    $item = menu_get_item();
    $block_id = substr($block->delta, 4);
    if (isset($item['page_arguments'][0]) && is_object($item['page_arguments'][0]) && (get_class($item['page_arguments'][0]) == 'IslandoraFedoraObject')) {
      $path = drupal_get_path('module', 'islandora_datastream_blocks_html_teaser');
      drupal_add_css("$path/css/block_teaser.css");
      $fedora_object = $item['page_arguments'][0];
      // get the matching datastream - to protect against this datastream being the wrong mimetype
      if (is_object($fedora_object) && (isset($fedora_object[$block_id])) && ($fedora_object[$block_id]->mimetype == 'text/html') ) {
        $data['content'] = _insert_break_if_none($data['content'], $block->delta);
      }
    }
  }
}

/**
 * Helper function to insert a DRUPAL_BREAK comment into a block that has none yet
 */
function _insert_break_if_none($content, $block_delta) {
  $retval = $content;
  if (strpos(DRUPAL_BREAK, $content) < 1) {
    $pre = strpos($content, "</p>") + 4;
    preg_match_all('/<\/p>/', $content, $matches, PREG_OFFSET_CAPTURE);
    $pre = (isset($matches[0][1][1])) ? $matches[0][1][1] :
      (isset($matches[0][2][1])) ? $matches[0][2][1] :
      (isset($matches[0][3][1])) ? $matches[0][3][1] : $pre;
    if ($pre <> 4) {
      $span_id = $block_delta.'_more';
      $div_id = $block_delta.'_collapse';
      $show_all_link = '<span id="' . $span_id. '" class="span-like-link">More...</span>';
      $content = ' <script type="text/javascript">                                         
   jQuery(document).ready(function() {
     jQuery("#' . $span_id . '").click(function() {
       jQuery("#' . $div_id . '").toggle();
       if (jQuery("#' . $span_id . '").html() !== "More...") {
         jQuery("#' .$span_id . '").html("More...");
       } else {
         jQuery("#' .$span_id . '").html("Less...");
       }
     });
   });
 </script> '."\n".
        substr($content, 0, $pre) . "\n".
        DRUPAL_BREAK . "\n".
        $show_all_link.'<div id="' . $div_id . '" style="display:none">' .
        substr($content, $pre).'</div> <!-- trick class -->';
    }
    $retval = $content;
  }
  return $retval;
}