<?php

/**
 * Implements hook_block_view_alter().
 */
function islandora_datastream_blocks_html_teaser_block_view_alter(&$data, $block) {
  if ($block->module == 'islandora_datastream_blocks') {
    $block_id = substr($block->delta, 4);
    $item = menu_get_item();
    if (isset($item['page_arguments'][0]) && is_object($item['page_arguments'][0]) && (get_class($item['page_arguments'][0]) == 'IslandoraFedoraObject')) {
      $fedora_object = $item['page_arguments'][0];
      // get the matching datastream - to protect against this datastream being the wrong mimetype
      if (is_object($fedora_object) && (isset($fedora_object[$block_id])) && ($fedora_object[$block_id]->mimetype == 'text/html') ) {
        $data['content'] = _insert_break_if_none($data['content'], $block->delta);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function islandora_datastream_blocks_html_teaser_theme() {
  return array(
    // Default object template.
    'block_with_teaser' => array(
      'template' => 'block-with-teaser',
      'variables' => array('content_before_break'=> NULL,
        'content_after_break' => NULL,
        'div_id' => '',
        'link_id' => '',
      )
    ));
}

/**
 * Helper function to insert a <!--break--> comment into a block that has none yet
 */
function _insert_break_if_none($content, $block_delta) {
  $retval = $content;
  if (strpos($content, '<!--break-->') < 1) {
    preg_match_all('/<\/p>/', $content, $matches, PREG_OFFSET_CAPTURE);
    $pre = (isset($matches[0][1][1])) ? $matches[0][1][1] :
      (isset($matches[0][2][1])) ? $matches[0][2][1] :
      (isset($matches[0][3][1])) ? $matches[0][3][1] : strpos($content, "</p>");
  }
  else {
    $pre = strpos($content, '<!--break-->');
  }
  if ($pre <> 4) {
    $link_id = $block_delta.'_more';
    $div_id = $block_delta.'_collapse';
    $content_before_break = substr($content, 0, $pre);
    $content_after_break = substr($content, $pre);
    $retval = theme('block_with_teaser', array('content_before_break'=> $content_before_break,
      'content_after_break' => $content_after_break,
      'div_id' => $div_id,
      'link_id' => $link_id,
      ));
  }
  return $retval;
}
